# Generated by Django 5.1.6 on 2026-03-01 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Min Price Fetching', 'Vinted Conversation Scraping'", max_length=255, unique=True)),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'min-price-fetching', 'vinted-conversation-scraping')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('celery_task', models.CharField(max_length=255)),
                ('cookies_file', models.FileField(blank=True, null=True, upload_to='task_cookies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='task_is_active_idx'), models.Index(fields=['name'], name='task_name_idx'), models.Index(fields=['slug'], name='task_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Task-specific input parameters')),
                ('progress', models.JSONField(blank=True, default=dict, help_text='Task-specific progress data', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.task')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status'], name='taskrun_status_idx'), models.Index(fields=['task', 'status'], name='taskrun_task_status_idx'), models.Index(fields=['started_at'], name='taskrun_started_at_idx')],
            },
        ),
    ]
