# Generated by Django 5.1.6 on 2026-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='logs_file',
            field=models.FileField(blank=True, null=True, upload_to='taskruns/logs/'),
        ),
    ]
