# Generated by Django 5.1.6 on 2026-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskrun_logs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
