# Generated by Django 5.1.6 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskrun_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allow_concurrent_runs',
            field=models.BooleanField(
                default=False,
                help_text='Allow multiple runs of this task to execute at the same time.',
            ),
        ),
    ]
