# Generated by Django 5.1.6 on 2026-03-11 00:00

from django.db import migrations


def register_vinted_purchase_completion_task(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    existing_vinted_task = Task.objects.filter(slug='vinted-conversation-scraping').first()
    defaults = {
        'name': 'Vinted Purchase Completion',
        'description': 'Completes an approved Vinted purchase in the background.',
        'celery_task': 'complete_vinted_purchase_task',
        'allow_concurrent_runs': True,
        'is_active': True,
    }
    if existing_vinted_task and existing_vinted_task.cookies_file:
        defaults['cookies_file'] = existing_vinted_task.cookies_file

    Task.objects.update_or_create(
        slug='vinted-purchase-completion',
        defaults=defaults,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_allow_concurrent_runs'),
    ]

    operations = [
        migrations.RunPython(register_vinted_purchase_completion_task, migrations.RunPython.noop),
    ]
