# Generated by Django 5.1.6 on 2026-03-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_register_vinted_purchase_completion_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskrun",
            old_name="error_message",
            new_name="detail",
        ),
    ]
