# Generated by Django 5.1.6 on 2026-03-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_taskrun_error_message_to_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskrun',
            options={'ordering': ['-id'], 'permissions': [('can_view_own_task_runs', 'View own task runs'), ('can_view_all_task_runs', 'View all task runs'), ('can_view_task_runs_month', 'View task runs within current month'), ('can_view_success_task_runs', 'View success task runs'), ('can_view_failed_task_runs', 'View failed task runs'), ('can_view_active_task_runs', 'View running/pending task runs'), ('can_start_task', 'Start task'), ('can_cancel_own_task_run', 'Cancel own task run'), ('can_cancel_any_task_run', 'Cancel any task run'), ('can_rerun_own_task_run', 'Rerun own task run'), ('can_rerun_any_task_run', 'Rerun any task run'), ('can_delete_own_task_run', 'Delete own task run'), ('can_delete_any_task_run', 'Delete any task run'), ('can_view_task_summary', 'View task summary')]},
        ),
    ]
