openapi: 3.0.3
info:
  title: Scriptify Backend API
  version: 1.0.0
  description: API documentation for Scriptify Backend
paths:
  /api/user/profile/:
    get:
      operationId: api_user_profile_retrieve
      description: Retrieves the authenticated user's profile information
      summary: Get user profile
      tags:
      - User Profile
      security:
      - OAuth2: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      phone_number:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      age:
                        type: integer
                      bio:
                        type: string
                      photo:
                        type: string
                      reading_goal:
                        type: integer
                      current_reading_streak:
                        type: integer
                      date_joined:
                        type: string
          description: ''
    put:
      operationId: api_user_profile_update
      description: Updates the authenticated user's profile information
      summary: Update user profile
      tags:
      - User Profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      security:
      - OAuth2: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
          description: ''
  /api/user/register/:
    post:
      operationId: api_user_register_create
      description: Registers a new user and returns an OAuth2 token.
      summary: Register a new user
      tags:
      - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
        required: true
      security:
      - OAuth2: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                message: User registered successfully
                data:
                  access_token: B6YSNgMmjlRVh2DVe1wzwD8X8Id4oO
                  expires_in: 86400
                  token_type: Bearer
                  scope: read write
                  refresh_token: j41z6KcxMaPGXGbSQy6Obp2HsN0RrL
          description: ''
        '400':
          content:
            application/json:
              schema:
                error: string
          description: ''
        '403':
          content:
            application/json:
              schema:
                detail: string
          description: ''
  /oauth/token/:
    post:
      operationId: oauth_token_create
      description: |-
        Implements an endpoint to provide access tokens

        The endpoint is used in the following flows:
        * Authorization code
        * Password
        * Client credentials
      tags:
      - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InlineTokenRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/InlineTokenRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/InlineTokenRequest'
        required: true
      security:
      - OAuth2: []
      - {}
      responses:
        '200':
          description: No response body
  /oauth/token/refresh/:
    post:
      operationId: oauth_token_refresh_create
      description: Handles OAuth2 token refresh
      tags:
      - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
        required: true
      security:
      - OAuth2: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshTokenResponse'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ''
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
      required:
      - error
    InlineTokenRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
        grant_type:
          type: string
          minLength: 1
        client_id:
          type: string
          minLength: 1
        client_secret:
          type: string
          minLength: 1
      required:
      - client_id
      - client_secret
      - grant_type
      - password
      - username
    RefreshTokenRequest:
      type: object
      properties:
        refresh_token:
          type: string
          minLength: 1
        grant_type:
          type: string
          minLength: 1
          default: refresh_token
        client_id:
          type: string
          minLength: 1
        client_secret:
          type: string
          minLength: 1
      required:
      - client_id
      - client_secret
      - refresh_token
    RefreshTokenResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
      required:
      - access_token
      - expires_in
      - refresh_token
      - token_type
    RegisterUserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
          maxLength: 254
        first_name:
          type: string
          minLength: 1
          maxLength: 50
        last_name:
          type: string
          minLength: 1
          maxLength: 50
        password:
          type: string
          writeOnly: true
          minLength: 1
          maxLength: 128
        confirm_password:
          type: string
          writeOnly: true
          minLength: 1
        client_id:
          type: string
          writeOnly: true
          minLength: 1
        client_secret:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - client_id
      - client_secret
      - confirm_password
      - email
      - first_name
      - last_name
      - password
    UserRequest:
      type: object
      properties:
        first_name:
          type: string
          minLength: 1
          maxLength: 50
        last_name:
          type: string
          minLength: 1
          maxLength: 50
        photo:
          type: string
          format: binary
          nullable: true
      required:
      - first_name
      - last_name
  securitySchemes:
    oauth2:
      type: oauth2
      flows: {}
