# Generated by Django 5.1.6 on 2026-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['first_name'], name='user_first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['last_name'], name='user_last_name_idx'),
        ),
    ]
