# Generated by Django 5.1.6 on 2026-03-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_options_myuser_user_email_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': [('can_assign_roles', 'Assign roles to users')]},
        ),
    ]
