# Generated by Django 5.1.6 on 2026-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('RECEIVED', 'Received'), ('PAID', 'Paid')], max_length=20)),
                ('transaction_from', models.CharField(max_length=255)),
                ('transaction_to', models.CharField(max_length=255)),
            ],
        ),
    ]
