# Generated by Django 5.1.6 on 2026-01-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_images/')),
                ('vendor_vat', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['vendor_name'],
            },
        ),
    ]
