# Generated by Django 5.1.6 on 2026-01-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], max_length=20, null=True),
        ),
    ]
