# Generated by Django 5.1.6 on 2026-01-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['vendor_name', '-id']},
        ),
    ]
