# Generated by Django 5.1.6 on 2026-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_transaction_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
