# Generated by Django 5.1.6 on 2026-03-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-id'], 'permissions': [('can_bulk_import_transactions', 'Bulk import transactions')]},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['vendor_name', '-id'], 'permissions': [('can_manage_vendors', 'Manage transaction vendors')]},
        ),
    ]
