# Generated by Django 5.1.6 on 2026-03-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_options_alter_vendor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-id'], 'permissions': [('can_bulk_import_transactions', 'Bulk add transactions'), ('can_import_transactions_from_file', 'Import transactions from file')]},
        ),
    ]
