# Generated by Django 5.1.6 on 2026-03-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-id'], 'permissions': [('can_import_transactions_from_file', 'Import transactions from file')]},
        ),
    ]
