# Generated by Django 5.1.6 on 2026-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('store', models.CharField(blank=True, max_length=255, null=True)),
                ('image_urls', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
