# Generated by Django 5.1.6 on 2026-01-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inventory_vendors/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_vendor',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'shelf',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Asin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ean', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multiple', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='listings.asin')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asins', to='listings.inventoryvendor')),
                ('shelf', models.ManyToManyField(blank=True, related_name='asins', to='listings.shelf')),
            ],
            options={
                'db_table': 'asin',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_url', models.CharField(max_length=1000)),
                ('picture_urls', models.JSONField(help_text='JSON array of image URLs: ["url1", "url2", ...]')),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'listing',
                'ordering': ['-timestamp', '-id'],
                'managed': True,
                'indexes': [models.Index(fields=['listing_url'], name='listing_url_idx'), models.Index(fields=['timestamp'], name='listing_timestamp_idx'), models.Index(fields=['price'], name='listing_price_idx'), models.Index(fields=['tracking_number'], name='listing_tracking_number_idx'), models.Index(fields=['timestamp', 'price'], name='listing_timestamp_price_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingAsin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('asin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asins_listings', to='listings.asin')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings_asins', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_asin',
                'ordering': ['-id'],
                'managed': True,
                'indexes': [models.Index(fields=['listing', 'asin'], name='listing_asin_composite_idx'), models.Index(fields=['listing'], name='listing_asin_listing_idx'), models.Index(fields=['asin'], name='listing_asin_asin_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asin',
            index=models.Index(fields=['value'], name='asin_value_idx'),
        ),
    ]
