# Generated by Django 5.1.6 on 2026-01-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingasin',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='asin',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
