# Generated by Django 5.1.6 on 2026-01-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listingasin_options_alter_asin_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asin',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
