# Generated by Django 5.1.6 on 2026-01-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-timestamp', '-id']},
        ),
    ]
