# Generated by Django 5.1.6 on 2026-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_asin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryvendor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'ordering': ['id']},
        ),
    ]
