# Generated by Django 5.1.6 on 2026-01-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='url',
            new_name='listing_url',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='listing',
            name='picture_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
