# Generated by Django 5.1.6 on 2026-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_inventoryvendor_options_alter_shelf_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryvendor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
