# Generated by Django 5.1.6 on 2026-01-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_inventoryvendor_name_alter_shelf_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryvendor',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
