# Generated by Django 5.1.6 on 2026-01-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_inventoryvendor_options_alter_shelf_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asin',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
