# Generated by Django 5.1.6 on 2026-02-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_asin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asin',
            options={'managed': False, 'ordering': ['-id']},
        ),
    ]
