# Generated by Django 5.1.6 on 2026-02-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_buildlog_buildlogitem_buildcomponent_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='InventoryColor',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('pattern', models.CharField(help_text="Color pattern name (e.g., 'magenta', 'red', 'cyan')", max_length=255, unique=True)),
        #         ('color', models.CharField(help_text="Hex color code (e.g., '#FF00FF')", max_length=7)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'db_table': 'inventory_color',
        #         'ordering': ['pattern'],
        #         'indexes': [models.Index(fields=['pattern'], name='inventory_color_pattern_idx')],
        #     },
        # ),
    ]
