# Generated by Django 5.1.6 on 2026-03-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_minpricetask_id_buildlog_buildlogitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingasin',
            options={'ordering': ['-id']},
        ),
    ]
