# Generated by Django 5.1.6 on 2026-03-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listingasin_options'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingasin',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_asins', to='purchases.purchases'),
        ),
    ]
