# Generated by Django 5.1.6 on 2026-03-07 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_minpricetask_alter_listingasin_options_buildlog_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='MinPriceTask',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
        #         ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
        #         ('total_asins', models.IntegerField(default=0)),
        #         ('processed_asins', models.IntegerField(default=0)),
        #         ('started_at', models.DateTimeField(blank=True, null=True)),
        #         ('finished_at', models.DateTimeField(blank=True, null=True)),
        #         ('error_message', models.TextField(blank=True, default='')),
        #     ],
        #     options={
        #         'db_table': 'min_price_task',
        #         'ordering': ['-id'],
        #     },
        # ),
        # migrations.AlterModelOptions(
        #     name='listingasin',
        #     options={'managed': False, 'ordering': ['-id']},
        # ),
        # migrations.CreateModel(
        #     name='BuildLog',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity', models.PositiveIntegerField()),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('is_reverted', models.BooleanField(default=False)),
        #         ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_logs', to='listings.asin')),
        #     ],
        #     options={
        #         'db_table': 'build_log',
        #         'ordering': ['-timestamp'],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='BuildLogItem',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity_consumed', models.PositiveIntegerField()),
        #         ('build_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='listings.buildlog')),
        #         ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.asin')),
        #     ],
        #     options={
        #         'db_table': 'build_log_item',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='InventoryColor',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('pattern', models.CharField(help_text="Color pattern name (e.g., 'magenta', 'red', 'cyan')", max_length=255, unique=True)),
        #         ('color', models.CharField(help_text="Hex color code (e.g., '#FF00FF')", max_length=7)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'db_table': 'inventory_color',
        #         'ordering': ['pattern'],
        #         'indexes': [models.Index(fields=['pattern'], name='inventory_color_pattern_idx')],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='BuildComponent',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity', models.PositiveIntegerField(default=1)),
        #         ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_set', to='listings.asin')),
        #         ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_set', to='listings.asin')),
        #     ],
        #     options={
        #         'db_table': 'build_component',
        #         'ordering': ['parent', 'component'],
        #         'indexes': [models.Index(fields=['parent'], name='build_comp_parent_idx'), models.Index(fields=['component'], name='build_comp_comp_idx')],
        #         'unique_together': {('parent', 'component')},
        #     },
        # ),
        # migrations.AddIndex(
        #     model_name='buildlog',
        #     index=models.Index(fields=['parent_item'], name='build_log_parent_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='buildlog',
        #     index=models.Index(fields=['timestamp'], name='build_log_timestamp_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='buildlog',
        #     index=models.Index(fields=['is_reverted'], name='build_log_reverted_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='buildlogitem',
        #     index=models.Index(fields=['build_log'], name='build_log_item_log_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='buildlogitem',
        #     index=models.Index(fields=['component'], name='build_log_item_comp_idx'),
        # ),
    ]
