# Generated by Django 5.1.6 on 2026-04-02 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_minpricetask_alter_asin_options_buildlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='MinPriceTask',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
        #         ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
        #         ('total_asins', models.IntegerField(default=0)),
        #         ('processed_asins', models.IntegerField(default=0)),
        #         ('started_at', models.DateTimeField(blank=True, null=True)),
        #         ('finished_at', models.DateTimeField(blank=True, null=True)),
        #         ('error_message', models.TextField(blank=True, default='')),
        #     ],
        #     options={
        #         'db_table': 'min_price_task',
        #         'ordering': ['-id'],
        #     },
        # ),
        # migrations.AlterModelOptions(
        #     name='asin',
        #     options={'managed': False, 'ordering': ['-id'], 'permissions': [('can_bulk_add_inventory', 'Bulk add inventory items'), ('can_import_inventory_from_file', 'Import inventory items from file'), ('can_update_inventories', 'Update inventories'), ('can_fetch_min_prices', 'Fetch min prices task')]},
        # ),
        # migrations.CreateModel(
        #     name='BuildLog',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity', models.PositiveIntegerField()),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('is_reverted', models.BooleanField(default=False)),
        #         ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_logs', to='listings.asin')),
        #     ],
        #     options={
        #         'db_table': 'build_log',
        #         'ordering': ['-timestamp'],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='BuildLogItem',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity_consumed', models.PositiveIntegerField()),
        #         ('build_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='listings.buildlog')),
        #         ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.asin')),
        #     ],
        #     options={
        #         'db_table': 'build_log_item',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='InventoryColor',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('pattern', models.CharField(help_text="Color pattern name (e.g., 'magenta', 'red', 'cyan')", max_length=255, unique=True)),
        #         ('color', models.CharField(help_text="Hex color code (e.g., '#FF00FF')", max_length=7)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'db_table': 'inventory_color',
        #         'ordering': ['pattern'],
        #         'permissions': [('can_manage_colors', 'Manage inventory colors')],
        #         'indexes': [models.Index(fields=['pattern'], name='inventory_color_pattern_idx')],
        #     },
        # ),
        migrations.CreateModel(
            name='InventoryUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('range_start', models.DateTimeField(blank=True, null=True)),
                ('range_end', models.DateTimeField(blank=True, null=True)),
                ('updated_count', models.IntegerField(default=0)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_update_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        # migrations.CreateModel(
        #     name='BuildComponent',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity', models.PositiveIntegerField(default=1)),
        #         ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_set', to='listings.asin')),
        #         ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_set', to='listings.asin')),
        #     ],
        #     options={
        #         'db_table': 'build_component',
        #         'ordering': ['parent', 'component'],
        #         'indexes': [models.Index(fields=['parent'], name='build_comp_parent_idx'), models.Index(fields=['component'], name='build_comp_comp_idx')],
        #         'unique_together': {('parent', 'component')},
        #     },
        # ),
        # migrations.AddIndex(
        #     model_name='buildlog',
        #     index=models.Index(fields=['parent_item'], name='build_log_parent_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='buildlog',
        #     index=models.Index(fields=['timestamp'], name='build_log_timestamp_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='buildlog',
        #     index=models.Index(fields=['is_reverted'], name='build_log_reverted_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='buildlogitem',
        #     index=models.Index(fields=['build_log'], name='build_log_item_log_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='buildlogitem',
        #     index=models.Index(fields=['component'], name='build_log_item_comp_idx'),
        # ),
        migrations.AddIndex(
            model_name='inventoryupdatelog',
            index=models.Index(fields=['applied_at'], name='inv_update_log_at_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryupdatelog',
            index=models.Index(fields=['applied_by'], name='inv_update_log_by_idx'),
        ),
    ]
