"""
Django settings for scriptify_backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "daphne",
    'django_eventstream',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'oauth2_provider',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'corsheaders',
    'api',
    'apps.user',
    'apps.scripts',  # Add scripts app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "django.middleware.common.CommonMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware'
]

ROOT_URLCONF = 'scriptify_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scriptify_backend.wsgi.application'
ASGI_APPLICATION = 'scriptify_backend.asgi.application'

REST_FRAMEWORK = {             
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', 
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': ('oauth2_provider.contrib.rest_framework.OAuth2Authentication',),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'django_eventstream.renderers.SSEEventRenderer',  # ← SSE
        'django_eventstream.renderers.BrowsableAPIEventStreamRenderer',  # ← Browsable SSE
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

APP_ENV = os.getenv('APP_ENV', 'local')

if APP_ENV == 'local':
    REDIS_HOST = "localhost"
elif APP_ENV == 'prod':
    REDIS_HOST = 'redis'
print("REDIS_HOST", REDIS_HOST)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', f"redis://:{os.getenv('REDIS_PASSWORD')}@{REDIS_HOST}:6379/0")
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', f"redis://:{os.getenv('REDIS_PASSWORD')}@{REDIS_HOST}:6379/0")
print(CELERY_BROKER_URL)
print(CELERY_RESULT_BACKEND)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 120 # 120 minutes
CELERY_TASK_TIME_LIMIT = 60 * 125  # 125 minutes

# CORS_ALLOWED_ORIGINS = [
#     "http://142.93.106.180:3000",
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     os.getenv("FRONTEND_URL", "").strip("/"),
# ]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

APPEND_SLASH=False


EVENTSTREAM_REDIS = {  # For Celery workers
    'host': REDIS_HOST,  # Your Redis host
    'port': 6379,
    'password': os.getenv('REDIS_PASSWORD'),
    'db': 3
}

EVENTSTREAM_STORAGE_CLASS = "django_eventstream.storage.DjangoModelStorage"
EVENTSTREAM_ALLOW_ORIGINS = None
EVENTSTREAM_ALLOW_CREDENTIALS = True

EVENTSTREAM_MAX_AGE = 60 * 60 * 24 * 7

OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 86400,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400 * 30,  # 30 days
    'ROTATE_REFRESH_TOKEN': False,
    'ALLOW_PUBLIC_CLIENTS': True,
    'REQUEST_APPROVAL_PROMPT': 'auto',
    
    # Scopes
    'SCOPES': {
        'read': 'Read access to resources',
        'write': 'Write access to resources',
    },
    'DEFAULT_SCOPES': ['read', 'write'],
    
    # THIS IS THE KEY SETTING - Allowed grant types
    'ALLOWED_GRANT_TYPES': [
        'password',           # Resource Owner Password Credentials Grant
        'refresh_token',      # Refresh Token Grant
        # 'authorization-code',  # Uncomment if you need this
        # 'client-credentials',  # Uncomment if you need this
    ],
    
    # Backend
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}

CSRF_TRUSTED_ORIGINS = [
    "http://142.93.106.180:3000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    os.getenv("FRONTEND_URL", "").strip("/"),
]

SPECTACULAR_SETTINGS = {
    "TITLE": "Scriptify API",
    "DESCRIPTION": "API documentation for Scriptify Backend",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,

    # Keeps authorization after page refresh
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },

    "COMPONENT_SPLIT_REQUEST": True,
    
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "OAuth2PasswordBearer": {
                "type": "oauth2",
                "flows": {
                    "password": {
                        "tokenUrl": "/oauth/token/",
                        "scopes": {
                            "read": "Read access to resources",
                            "write": "Write access to resources",
                        },
                    },
                },
            }
        }
    },
    "SECURITY": [{"OAuth2PasswordBearer": ["read", "write"]}],
}


# OAUTH2_PROVIDER = {             
# # this is the dictionary of available scopes that will be visible to the user             
#   'SCOPES': {                 
#     'images': 'Create and get images',                 
#     'image': 'Read and delete an image'             
#   }         
# } 

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_USER = os.getenv('DB_USER', None)
DB_PASS = os.getenv('DB_PASSWORD', None)
DB_HOST = os.getenv('DB_HOST', None)
DB_PORT = os.getenv('DB_PORT', None)
DB_NAME = os.getenv('DB_NAME', None)
CLIENT_ID = os.getenv('CLIENT_ID', None)
CLIENT_SECRET = os.getenv('CLIENT_SECRET', None)


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASS,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'TEST': {
            'NAME': f'{DB_NAME}_test',  # This creates a dedicated test database
        },
    },
}


AUTH_USER_MODEL = 'user.MyUser'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
