"""
Django settings for scriptify_backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import os

# Configure PyMySQL to work with Django's MySQL backend
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("APP_ENV", "local") == "local" else False

# ALLOWED_HOSTS: List of allowed host/domain names
# Can be set via environment variable (comma-separated) or defaults to server IP and localhost
ALLOWED_HOSTS_ENV = os.getenv("ALLOWED_HOSTS", "")
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",") if host.strip()]
else:
    # Default allowed hosts: server IP and localhost for development
    ALLOWED_HOSTS = [
        "104.248.33.182",
        "localhost",
        "127.0.0.1",
    ]
    # Add BACKEND_URL if it exists
    backend_url = os.getenv("BACKEND_URL", "").strip("/")
    if backend_url:
        # Extract hostname from URL (remove protocol and path)
        from urllib.parse import urlparse
        parsed = urlparse(backend_url)
        if parsed.hostname:
            ALLOWED_HOSTS.append(parsed.hostname)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "daphne",
    'django_eventstream',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'oauth2_provider',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'corsheaders',
    'api',
    'apps.user',
    'apps.scripts',
    'apps.transactions',
    'apps.listings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "django.middleware.common.CommonMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware'
]

ROOT_URLCONF = 'scriptify_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scriptify_backend.wsgi.application'
ASGI_APPLICATION = 'scriptify_backend.asgi.application'

REST_FRAMEWORK = {             
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', 
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': ('oauth2_provider.contrib.rest_framework.OAuth2Authentication',),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'django_eventstream.renderers.SSEEventRenderer',  # ← SSE
        'django_eventstream.renderers.BrowsableAPIEventStreamRenderer',  # ← Browsable SSE
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

APP_ENV = os.getenv('APP_ENV', 'local')

if APP_ENV == 'local':
    REDIS_HOST = "localhost"
elif APP_ENV == 'prod':
    REDIS_HOST = 'redis'
# print("REDIS_HOST", REDIS_HOST)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', f"redis://:{os.getenv('REDIS_PASSWORD')}@{REDIS_HOST}:6379/0")
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', f"redis://:{os.getenv('REDIS_PASSWORD')}@{REDIS_HOST}:6379/0")
# print(CELERY_BROKER_URL)
# print(CELERY_RESULT_BACKEND)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 300 # 300 minutes
CELERY_TASK_TIME_LIMIT = 60 * 325  # 325 minutes

CORS_ALLOWED_ORIGINS = [
    "http://104.248.33.182",
    "https://104.248.33.182",
    "http://104.248.33.182:80",
    "https://104.248.33.182:443",
    "http://104.248.33.182:8000",  # External nginx port
    "https://104.248.33.182:8000",  # External nginx port (if using HTTPS)
    "http://104.248.33.182:3000",
    "https://104.248.33.182:3000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",  # For local development with nginx
    "http://127.0.0.1:8000",  # For local development with nginx
]

# Add FRONTEND_URL from environment if it exists
frontend_url = os.getenv("FRONTEND_URL", "").strip("/")
if frontend_url:
    CORS_ALLOWED_ORIGINS.append(frontend_url)

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

APPEND_SLASH=False


EVENTSTREAM_REDIS = {  # For Celery workers
    'host': REDIS_HOST,  # Your Redis host
    'port': 6379,
    'password': os.getenv('REDIS_PASSWORD'),
    'db': 3
}

EVENTSTREAM_STORAGE_CLASS = "django_eventstream.storage.DjangoModelStorage"
EVENTSTREAM_ALLOW_ORIGINS = None
EVENTSTREAM_ALLOW_CREDENTIALS = True

EVENTSTREAM_MAX_AGE = 60 * 60 * 24 * 7

OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 86400,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400 * 30,  # 30 days
    'ROTATE_REFRESH_TOKEN': False,
    'ALLOW_PUBLIC_CLIENTS': True,
    'REQUEST_APPROVAL_PROMPT': 'auto',
    
    # Scopes
    'SCOPES': {
        'read': 'Read access to resources',
        'write': 'Write access to resources',
    },
    'DEFAULT_SCOPES': ['read', 'write'],
    
    # THIS IS THE KEY SETTING - Allowed grant types
    'ALLOWED_GRANT_TYPES': [
        'password',           # Resource Owner Password Credentials Grant
        'refresh_token',      # Refresh Token Grant
        # 'authorization-code',  # Uncomment if you need this
        # 'client-credentials',  # Uncomment if you need this
    ],
    
    # Backend
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}

CSRF_TRUSTED_ORIGINS = [
    "http://104.248.33.182:8000",  # External nginx port
    "https://104.248.33.182:8000",  # External nginx port (if using HTTPS)
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",  # For local development with nginx
    "http://127.0.0.1:8000",  # For local development with nginx
]

# Add FRONTEND_URL from environment if it exists
frontend_url_csrf = os.getenv("FRONTEND_URL", "").strip("/")
if frontend_url_csrf:
    CSRF_TRUSTED_ORIGINS.append(frontend_url_csrf)

SPECTACULAR_SETTINGS = {
    "TITLE": "Scriptify API",
    "DESCRIPTION": "API documentation for Scriptify Backend",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,

    # Keeps authorization after page refresh
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },

    "COMPONENT_SPLIT_REQUEST": True,
    
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "OAuth2PasswordBearer": {
                "type": "oauth2",
                "flows": {
                    "password": {
                        "tokenUrl": "/oauth/token/",
                        "scopes": {
                            "read": "Read access to resources",
                            "write": "Write access to resources",
                        },
                    },
                },
            }
        }
    },
    "SECURITY": [{"OAuth2PasswordBearer": ["read", "write"]}],
}


# OAUTH2_PROVIDER = {             
# # this is the dictionary of available scopes that will be visible to the user             
#   'SCOPES': {                 
#     'images': 'Create and get images',                 
#     'image': 'Read and delete an image'             
#   }         
# } 

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_USER = os.getenv('DB_USER', None)
DB_PASS = os.getenv('DB_PASSWORD', None)
DB_HOST = os.getenv('DB_HOST', None)
DB_PORT = os.getenv('DB_PORT', None)
DB_NAME = os.getenv('DB_NAME', None)
CLIENT_ID = os.getenv('CLIENT_ID', None)
CLIENT_SECRET = os.getenv('CLIENT_SECRET', None)
CA_CERT_PATH = os.path.join(BASE_DIR, 'certs', 'ca-certificate.crt')

# Database configuration based on environment
if APP_ENV == 'local':
    # Use PostgreSQL for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASS,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            # Connection pooling for remote database performance
            'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
            'OPTIONS': {
                'connect_timeout': 30,  # Fail fast if DB is unreachable
                'options': '-c statement_timeout=30000',  # 30 second query timeout
            },
            'TEST': {
                'NAME': f'{DB_NAME}_test',  # This creates a dedicated test database
            },
        },
    }
else:
    # Use MySQL for production/other environments
    # Check if CA certificate file exists
    ssl_options = {}
    if os.path.exists(CA_CERT_PATH):
        ssl_options = {
            'ssl': {
                'ca': CA_CERT_PATH,
            }
        }
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASS,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            # Connection pooling for remote database performance
            'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes (reduces connection overhead)
            'OPTIONS': {
                **ssl_options,
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
                'connect_timeout': 30,  # Fail fast if DB is unreachable (seconds)
                'read_timeout': 30,  # Timeout for read operations (seconds)
                'write_timeout': 30,  # Timeout for write operations (seconds)
            },
            'TEST': {
                'NAME': f'{DB_NAME}_test',  # This creates a dedicated test database
            },
        },
    }


# Database performance optimizations
# Disable persistent connections in tests to avoid connection leaks
# if 'test' in sys.argv:
#     DATABASES['default']['CONN_MAX_AGE'] = 0

# Database query optimization settings
DATABASE_ROUTERS = []  # Add custom routers if needed

# Optimize database queries
# This helps reduce the number of queries by keeping connections alive
# CONN_MAX_AGE is set per database above (600 seconds = 10 minutes)

AUTH_USER_MODEL = 'user.MyUser'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Logging configuration for database query monitoring
# Enable this to identify slow queries (uncomment to enable)
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG' if DEBUG else 'INFO',
#         },
#     },
# }
