# Generated by Django 5.1.6 on 2025-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='input_file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
