# Generated by Django 5.1.6 on 2025-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_run_input_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='script_pics'),
        ),
        migrations.AlterField(
            model_name='script',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
