# Generated by Django 5.1.6 on 2025-11-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_script_pic_alter_script_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='cookies_file',
            field=models.FileField(blank=True, null=True, upload_to='cookies/'),
        ),
    ]
