# Generated by Django 5.1.6 on 2025-11-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_script_cookies_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='input_file_path',
        ),
        migrations.AddField(
            model_name='run',
            name='input_file_paths',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
