# Generated by Django 5.1.6 on 2025-11-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_remove_run_result_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='input_schema_snapshot',
            field=models.JSONField(blank=True, help_text='input_schema at the time of run creation', null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='output_schema_snapshot',
            field=models.JSONField(blank=True, help_text='output_schema at the time of run creation', null=True),
        ),
    ]
