# Generated by Django 5.1.6 on 2025-11-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_run_input_schema_snapshot_run_output_schema_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='logs_file_path',
        ),
        migrations.RemoveField(
            model_name='run',
            name='result_file_path',
        ),
        migrations.AddField(
            model_name='run',
            name='logs_file',
            field=models.FileField(blank=True, null=True, upload_to='runs/logs/'),
        ),
        migrations.AddField(
            model_name='run',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='runs/results/'),
        ),
    ]
