# Generated by Django 5.1.6 on 2025-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_remove_run_logs_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
