# Generated by Django 5.1.6 on 2025-11-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_alter_run_started_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-id']},
        ),
    ]
