# Generated by Django 5.1.6 on 2026-01-11 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_alter_run_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status'], name='run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['started_at'], name='run_started_at_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['finished_at'], name='run_finished_at_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['script', 'status'], name='run_script_status_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['script', 'started_at'], name='run_script_started_at_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['started_by', 'started_at'], name='run_started_by_started_at_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['is_active'], name='script_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['created_at'], name='script_created_at_idx'),
        ),
    ]
