# Generated by Django 5.1.6 on 2026-03-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0011_run_run_status_idx_run_run_started_at_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-id'], 'permissions': [('can_view_own_runs', 'View own script runs'), ('can_view_all_runs', 'View all script runs'), ('can_view_runs_month', 'View script runs within current month'), ('can_view_success_runs', 'View success script runs'), ('can_view_failed_runs', 'View failed script runs'), ('can_view_active_runs', 'View running/pending script runs'), ('can_abort_own_run', 'Abort own script run'), ('can_abort_any_run', 'Abort any script run'), ('can_view_run_logs', 'View run logs'), ('can_view_run_results', 'View run results'), ('can_delete_own_run', 'Delete own script run'), ('can_delete_any_run', 'Delete any script run')]},
        ),
    ]
