# Generated by Django 5.1.6 on 2026-02-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0014_alter_minpricetask_id_buildlog_buildlogitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('vinted', 'Vinted'), ('amazon', 'Amazon'), ('kleinanzeigen', 'Kleinanzeigen'), ('momox', 'Momox')], db_index=True, help_text='Platform source: vinted, amazon, kleinanzeigen, momox, etc.', max_length=50)),
                ('external_id', models.CharField(db_index=True, help_text='Platform-specific order/conversation ID', max_length=255)),
                ('seller_info', models.JSONField(blank=True, help_text='Platform-specific seller information (id, name, username, etc.)', null=True)),
                ('order_status', models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('uncompleted', 'Uncompleted')], db_index=True, max_length=50, null=True)),
                ('product_title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_listing_url', models.URLField(blank=True, help_text="Primary listing URL (first item's URL for bundles)", null=True)),
                ('purchased_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_fee_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('shipment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipment_price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunded_amount_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_code', models.CharField(blank=True, db_index=True, help_text='Tracking number for matching with Listing.tracking_number', max_length=255, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, help_text="Array of items: [{'title': '...', 'url': '...', 'price': '...', 'currency': '...', 'image_urls': [...]}]", null=True)),
                ('approved_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, max_length=20, null=True)),
                ('approved_rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('platform_data', models.JSONField(blank=True, help_text="Platform-specific fields that don't fit in generic structure", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='listings.listing')),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['platform', 'external_id'], name='purchases_platform_id_idx'), models.Index(fields=['platform'], name='purchases_platform_idx'), models.Index(fields=['order_status'], name='purchases_order_status_idx'), models.Index(fields=['approved_status'], name='purchases_approved_status_idx'), models.Index(fields=['purchased_at'], name='purchases_purchased_at_idx'), models.Index(fields=['updated_at'], name='purchases_updated_at_idx'), models.Index(fields=['tracking_code'], name='purchases_tracking_code_idx'), models.Index(fields=['listing'], name='purchases_listing_idx')],
                'unique_together': {('platform', 'external_id')},
            },
        ),
    ]
