# Generated by Django 5.1.6 on 2026-03-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='order_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('uncompleted', 'Uncompleted'), ('waiting', 'Waiting')], db_index=True, max_length=50, null=True),
        ),
    ]
