# Generated by Django 5.1.6 on 2026-03-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchases_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'ordering': ['-updated_at', '-id'], 'permissions': [('can_approve_purchase', 'Approve / reject purchase'), ('can_bulk_upsert_purchases', 'Bulk import purchases')]},
        ),
    ]
