# Generated by Django 5.1.6 on 2026-03-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchases_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'ordering': ['-updated_at', '-id'], 'permissions': [('can_approve_purchase', 'Approve / reject purchase'), ('can_bulk_upsert_purchases', 'Bulk add purchases'), ('can_import_purchases_from_file', 'Import purchases from file')]},
        ),
    ]
