# Generated by Django 5.1.6 on 2026-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchases_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='decision_note',
            field=models.TextField(blank=True, help_text='Optional note written by the reviewer when approving or rejecting', null=True),
        ),
    ]
